### ISSUE TITLE
DataTable enhancements

### ISSUE THREAD

**Issue by hlayisanimazuze** [shesha-io/shesha-framework#2603]
1. Add the following dataTable styling properties

| **Property**              | **Description**                                                                                              | **Example Values**                            |
|---------------------------|------------------------------------------------------------------------------------------------------------|-----------------------------------------------|
| `width`                   | Sets the overall width of the table.                                                                       | `auto`, `100%`, `800px`                       |
| `height`                  | Sets the overall height of the table (useful for scrollable tables).                                       | `auto`, `500px`                               |
| `border`                  | Specifies the style of the table border.                                                                   | `none`, `1px solid #ccc`                      |
| `background-color`        | Sets the background color of the table.                                                                    | `#fff`, `#f9f9f9`                             |
| `font-family`             | Defines the font style for the table text.                                                                 | `Arial`, `Roboto`, `sans-serif`               |
| `font-size`               | Sets the font size for the table text.                                                                     | `12px`, `14px`, `16px`                        |
| `overflow`                | Controls how content behaves when it exceeds the table dimensions.                                         | `auto`, `scroll`, `hidden`                    |
| `striped`                 | Enables alternating row colors for better readability.                                                     | `true`, `false`                               |
| `hover-highlight`         | Highlights a row on hover for better interactivity.                                                        | `true`, `false`                               |
| `sticky-header`           | Makes the table header stick to the top when scrolling.                                                    | `true`, `false`                               |
| `row-height`              | Sets the height of each row.                                                                               | `auto`, `40px`, `60px`                        |
| `row-background-color`    | Sets the background color of table rows.                                                                   | `#fff`, `#f9f9f9`                             |
| `row-hover-color`         | Specifies the background color of a row when hovered.                                                      | `#f0f0f0`, `#eaeaea`                          |
| `row-border`              | Defines the style of borders between rows.                                                                 | `none`, `1px solid #ddd`                      |
| `row-padding`             | Adds padding inside rows.                                                                                  | `8px`, `10px 15px`                            |
| `row-selected-color`      | Specifies the background color for selected rows.                                                          | `#d3e5ff`, `#e6f7ff`                          |
| `header-font-size`        | Specifies the font size for column headers.                                                                | `14px`, `16px`                                |
| `header-font-weight`      | Defines the weight (boldness) of header text.                                                              | `normal`, `bold`                              |
| `header-background-color` | Sets the background color of the header row.                                                               | `#f7f7f7`, `#333`                             |
| `header-text-color`       | Defines the text color of column headers.                                                                  | `#000`, `#fff`, `#666`                        |
| `header-border`           | Specifies the border style for the header row.                                                             | `none`, `1px solid #ddd`                      |
| `sortable-indicator-color`| Sets the color of sorting indicators (e.g., arrows).                                                       | `#000`, `#666`, `#007bff`                     |
| `zebra-stripe-color`      | Alternates row colors for zebra striping.                                                                  | `#fff`, `#f9f9f9`, `#eeeeee`                  |
| `border-radius`           | Defines the roundness of table corners.                                                                    | `0px`, `8px`                                  |
| `box-shadow`              | Applies a shadow around the table for better visual hierarchy.                                             | `none`, `0px 4px 8px rgba(0,0,0,0.1)`         |

2. SelectionMode - For data table currently 'multi-select' checkbox. Should probably be changed for consistency to align with DataList (assuming tables can disable selection)   - Selection Mode: 
      - None
      - Single
      - Multiple 
3. Add the following events:
    - onRowClick
   - onRowDoubleClick
   - onRowHover
   - onRowSelect
   - onSelectionChange
**Related to:** #1041.

**Comment by Tshepiso-R** [comment]
## Bugs / Issues
- [ ] **Event Tab variables**: Expose all variables (e.g., `data`, `pageContext`, `SelectedRow`, `GlobalState`, …) for the properties under **Event Tab**.  
- [ ] **On Selection Change**: Currently triggered on initial load and does not work as expected.  
- [ ] **Font alignment**: Works only in Designer, resets to default when rendered or refreshed.  
- [ ] **Selection mode**: No longer working.  
- [ ] **Borders**:  
  - In Designer → too many borders shown around containers.  
  - In Render → only one border shown.  
  - Should ideally apply to the **main table container**, not just the table body, and must also account for **inline creation row**.  
- [x] **Backgrounds**: Not working.  
- [x] **Padding/Margin**: Not working.  
- [ ] **Border radius**: Seems applied to the wrong container. 

<img width="1920" height="769" alt="Image" src="https://github.com/user-attachments/assets/d40f79a0-c2d9-4739-a9aa-40bea89213e6" />
 
- [ ] **Style property**: Not clear where it applies; currently not working.  

## Inconsistencies / UX Decisions
- [ ] **Overwrite behavior**: Since appearance is hidden for each component, allow overwrite. Currently, fonts only apply to the default display component.  
- [ ] **Font & Icon scaling**: Increasing font size also enlarges the **action column icon**, but not the **CRUD icons**. Need a **consistent behavior** decision.  
- [ ] **Highlighting**: Rows are always highlighted even when *Hover Highlight* is set to `false`.  
- [ ] **Striped rows**: Should be `true` by default. Also restore the old default background.  

## Missing Features (Not Implemented)

Ideally, properties should be separated into **Header**, **Table Body**, and **Overall Table** sections.  

- [ ] `header-font-size`  
- [ ] `header-font-weight`  
- [ ] `header-background-color`  
- [ ] `header-text-color`  

- [ ] `row-height`  
- [ ] `row-padding`  
- [ ] `row-border`  

- [ ] `box-shadow`  
- [ ] `sortable-indicator-color`

**Comment by miracleMa** [comment]
1. Selection Mode issues  :

- When the selection mode is set to either Single or Multiple, and you render the form, selecting a row causes the content of that row to disappear.**Because the selected  text  color changes to white  **
 (Video ref :https://jam.dev/c/32f2d3e6-4784-4b06-952c-9aa59c11dc63)

- Remove the checkboxes when selection mode = single but the rows must still be selectable (same as previous implementation   when "Use Multi-Select" was false )
- And  all previously configured data-table 
   if  "Use Multi-Select"  was false return "single " on the new selection mode property 
   If   "Use Multi-Select" was true return  "multiple" on the new selection mode property 

  

2.Table Styling issues

- All properties under table specific section are not working.  The only work for some part when  add the cell padding 
    https://jam.dev/c/0cbe2ef5-f4ec-4af8-8c4c-5994afe9be2b
<img width="281" height="322" alt="Image" src="https://github.com/user-attachments/assets/8341dfa0-088c-4f15-a152-5baa9944ffcf" />

- Add default values for the following properties 
 
<img width="274" height="142" alt="Image" src="https://github.com/user-attachments/assets/a9ecd155-b04f-468f-9e21-ec80232c4dcf" />

- Row border is  working
- Lets have default values for  font size and font weight on header styling 

- Column background Color is not working

<img width="1920" height="996" alt="Image" src="https://github.com/user-attachments/assets/4601c446-1c2c-43f7-b3a0-ec535fbb69d8" />

- If a background color is add on the table you can't see the  on hover highlight 
https://jam.dev/c/cf0c3cdc-9510-4d97-ab9f-e2eae4c521f9
- Shadow properties are not working 
  
<img width="288" height="113" alt="Image" src="https://github.com/user-attachments/assets/01368c96-a551-4f0e-9eae-642a027d35fe" />

- By default the datatable has this thick border, please address it

<img width="1920" height="779" alt="Image" src="https://github.com/user-attachments/assets/3f435edc-6d30-43fc-a80e-d7366308c0a8" />

- [ ] **Striped rows**: Should be `true` by default. Also restore the old default background.


3. Events

- When you configure the "On Row Double Click" event, it also triggers the "On Row Click" event twice.
- "On selection change" must be triggered only after moving from one selection to another. Currently, the "On selection   change" event is triggered even on the first selection or when there is no previously selected row.

**Comment by miracleMa** [comment]
Hi @HackGenesis  please reach out before you start working on this item .

**Comment by miracleMa** [comment]
**DataTable Issues**

1. When you set the selection mode to **single** or **multiple** and select a row, the row text still turns white.

2. Remove the checkboxes when **selection mode = single**, but the rows must still be selectable (same as the previous implementation when **“Use Multi-Select”** was false).

3. When you create a new DataTable, the table initially comes with **Striped Row** enabled, but the **Striped Row** property is set to **false**. After manually setting it to **true**, it works as expected.

<img width="1920" height="945" alt="Image" src="https://github.com/user-attachments/assets/298ae2d9-e694-4198-ac16-ed3592076fb7" />

4. Add default values for the following properties 
<img width="274" height="142" alt="Image" src="https://github.com/user-attachments/assets/a9ecd155-b04f-468f-9e21-ec80232c4dcf" />

5. Expose default values for font size and font weight on header styling
6. Table shadow properties are not working
7. Selection in DataTable works incorrect (example - Creating the form from template). See [the video](https://jam.dev/c/f67b9c95-89f5-4f9f-a98a-bc3f5d8d6970)
8. Selection mode should be Single by default (previous DataTable behaviour)

**Comment by Tshepiso-R** [comment]
## Visual & Styling Issues

- [x] **Stripe color too faint** - Revert to v43 default stripe color (current main branch color is too light)

- [x] **Header font styling changed** - Restore original default font weight and size for table header

- [x] **Content spacing issue** - Table content and headers are too close to the right border, needs proper padding

- [x] **Header alignment changed** - Header is now top-aligned, restore previous alignment

![Header alignment issue](https://github.com/user-attachments/assets/b88f9846-c5f5-4344-96de-8e16fb5be85e)

- [x] **Selected row styling broken** - When selecting a striped row, both background and font color turn white (should maintain contrast/visibility)

- [x] **Row padding styles not applied** - Configured values in Row Padding style box have no effect

![Row padding configuration](https://github.com/user-attachments/assets/836c9bb1-0a52-458f-9da7-7cb63c0da00f)

- [x] **Font weight not working** - Font weight property not applying as expected

- [ ] **Backgrounds not working** - Only color works; other background properties fail

- [x] **Shadow not working** - Shadow styling not applying as expected

- [x] **Padding & Margin not working** - Padding and margin configurations not applying properly

- [ ] **Cell background rendering as borders** - Background color for table cells appears as borders instead of fill

![Cell background issue](https://github.com/user-attachments/assets/dda19b8c-43ce-404a-a9ca-5b187657601f)

- [ ] **Tags component white background** - When tags are used and row is selected, white background appears (ensure "show solid color" is false)

![Tags white background issue](https://github.com/user-attachments/assets/8c8d4be6-e866-445e-8a87-67215e6c91f1)

## Configuration & Properties Issues

- [x] **Striped rows default mismatch** - Striped rows display by default but property shows false (set property default to true)

- [x] **Hover highlight default** - Set "Hover Highlight" to true by default (retain old behavior)

- [x] **Conditional property visibility** - "Selected Background", "On Selection Change", and "On Row Select" should only display when Selection Mode is not "None"

- [x] **Row Height missing defaults** - Add default value for Row Height property

- [x] **Missing tooltips** - Add tooltips for Min Height and Max Height fields

![Min/Max Height fields](https://github.com/user-attachments/assets/2936c0ca-926d-4255-afee-c9d3aad66f5e)

- [x] **Row Padding naming** - Rename "Row Padding" style box (contains margin as well, so name is misleading)

## Layout & Structure Issues

- [x] **Duplicate Border sections** - Two Border sections exist (one without input), remove duplicate

![Duplicate Border sections](https://github.com/user-attachments/assets/e0a17313-da58-4d29-a48e-165aea39407f)

- [x] **Header color properties misplaced** - Move "Header Font Color" and "Header Background Color" to Header Styling section, align side-by-side, remove redundant "header" text in labels

- [x] **Section naming** - Rename "Header Styling" → "Header Styles" and "Table Body Styling" → "Table Body Styles"

## Functionality Issues

- [ ] **Selection mode change clears content** - Changing selection mode causes table content to disappear and placeholder to appear (default datatable columns resurface during configuration)

https://github.com/user-attachments/assets/a6080cce-3444-4b2d-9ec7-d2b113ef63b5

- [x] **Multiple selection broken** - Multiple selection mode not working, cannot select rows

[Video: Multiple selection issue](https://jam.dev/c/5c783977-fd8f-4580-8e4d-1de4fde0a8c3)

- [x] **Font alignment scope limited** - Font Alignment only affects header when display component is NOT default (needs to work consistently; It has been discussed with @James-Baloyi to expose styles for display/edit/create components). Font style also only takes effect when display component is default

![Font alignment issue](https://github.com/user-attachments/assets/71a960cb-d7bb-4db6-8c6f-f09b2aa112a4)

- [x] **Sticky Header not working** - Sticky header functionality not functioning

- [x] **Style code editor not working** - Code editor for styles is non-functional

- [x] **Style tooltips and application** - Provide tooltips for Style, Table Style, and Container Style properties; background not applying for Table Style and Container Style

- [x] **Anchor column not fixed** - When anchor is configured, column is not fixed on scroll (gets scrolled and hidden)

- [x] **Anchor removes styles** - Configuring anchor causes previously configured styles (e.g., font color) to be lost

## Event Handling Issues

- [ ] **Selected row logging offset** - Console logging selectedRow on onClick: first row click logs null, second row click logs first row object (off-by-one issue)

- [ ] **Dialog display offset** - Show dialog on click: first click doesn't show details, second click shows first record's details (affects onClick, onDoubleClick, onSelect)

- [ ] **Navigate action query parameters broken** - Using `selectedRow.id` in query parameters for navigate action on onClick/onDoubleClick doesn't pull the ID correctly

**Comment by Tshepiso-R** [comment]
- [x] **Stripe color too faint** - Revert to v43 default stripe color (current main branch color is too light) - **Not Implemented**

- [x] **Header font styling changed** - Restore original default font weight and size for table header - **Not Implemented**

- [x] **Shadow not working** - Shadow styling not applying as expected - **Not Implemented**, we should be able to see the shadow without configuring margins just like other components

- [x] **Backgrounds not working** - Only color works; other background properties fail - **Not Implemented - Awaiting @teboho**

- [x] **Tags component white background** - When tags are used and row is selected, white background appears (ensure "show solid color" is false) - **Not Implemented - Awaiting @teboho**

- [ ] **Selection mode change clears content** - Changing selection mode causes table content to disappear and placeholder to appear (default datatable columns resurface during configuration) - **Not Implemented - Awaiting @teboho**

![Video](https://github.com/user-attachments/assets/a6080cce-3444-4b2d-9ec7-d2b113ef63b5)

- [x] **Row Padding naming** - Rename "Row Padding" style box (contains margin as well, so name is misleading) - **Not Implemented**

- [x] **Striped rows default mismatch** - Striped rows display by default but property shows false (set property default to true) - **Not Implemented**

- [x] **Multiple selection broken** - Multiple selection mode not working, cannot select rows - **Not Implemented**

- [ ] **Sticky Header not working** - Sticky header functionality not functioning - **Not Implemented**

- [ ] **Anchor removes styles** - Configuring anchor causes previously configured styles (e.g., font color) to be lost - **Not Implemented**

---

- [x] **Selection mode implementation** - Please revert to the previous implementation. Single mode should not show checkboxes

- [x] **Icon too small** - Icon size is smaller compared to the previous version

![Image](https://github.com/user-attachments/assets/a52d6024-264f-4ad6-a6c9-fc1e41e6467e)

- [x] **Selected row styling broken** - When selecting a striped row, both background and font color turn white (should maintain contrast/visibility)
  - *Fixed but broke the row without the striped color*

![Image](https://github.com/user-attachments/assets/10233da0-c92e-477f-b2b8-fec18955fb4d)

- [ ] **Cell padding not correctly applied** - Additionally, as soon as you set top and bottom padding, the content touches the left borders of the cell. Please set default values to avoid this. Please make sure you remove margin, rather use inputs than to expose margin as it does not work

![Image](https://github.com/user-attachments/assets/f504c2d0-199e-4ef3-9c7b-77ecbb447193)

- [x] **Font alignment not working** - Font alignment is not working for table body

- [x] **Padding & Margin still not applying correctly**

- [x] **Hover highlight default** - Set "Hover Highlight" to true by default (retain old behavior) - **Not fully implemented**, the property is still false by default

- [x] **Font property inconsistency** - Please use the standard font property same as Font section

![Image](https://github.com/user-attachments/assets/97733ec1-1cc5-43e0-b9b1-2c03920c0e1c)

- [x] **Custom Styles placement** - Custom Styles should always be at the bottom

- [x] **Row Border is missing**

- [ ] **Side by side display** - Implement side by side display

![Image](https://github.com/user-attachments/assets/d225e7e3-f805-4b75-90bb-2faacbc59eb9)

- [ ] **Style and Table Style not working**

- [x] **Table Body font applying to header** - Table body font should only be applied to the body, not the header

---

**Event Handling Issues (Awaiting discussion with @ihouvet):**

- [x] **Selected row logging offset** - Console logging selectedRow on onClick: first row click logs null, second row click logs first row object (off-by-one issue)

- [x] **Dialog display offset** - Show dialog on click: first click doesn't show details, second click shows first record's details (affects onClick, onDoubleClick, onSelect)

- [x] **Navigate action query parameters broken** - Using `selectedRow.id` in query parameters for navigate action on onClick/onDoubleClick doesn't pull the ID correctly

- [x] Icons on the reordering columns have differnt sizes

<img width="1920" height="872" alt="Image" src="https://github.com/user-attachments/assets/d001460d-d93a-46e6-ae14-cc1e77eb04e9" />

- [ ] form fields are cut out when form column type is used on row edit and display

<img width="1920" height="930" alt="Image" src="https://github.com/user-attachments/assets/18712806-6105-415a-9b82-3836a36e9d6d" />

**Comment by Tshepiso-R** [comment]
- [x] **Icon too small** – The icon size in the Action column is smaller than expected. It should match the size of the Action column, and the CRUD column icons should be center-aligned.

<img width="1920" height="911" alt="Icon too small" src="https://github.com/user-attachments/assets/6bcb1e45-8630-4f77-888c-d979a57e27ae" />

- [x] When using a dropdown for display, it appears with backgrounds.

<img width="1920" height="636" alt="Dropdown background issue" src="https://github.com/user-attachments/assets/a6f5b425-bbba-4af6-b520-338aa8214b72" />

- [x] When using a dropdown for display with **Display Type = Tags** and **Mode = Multiple**, the values overlap.

<img width="1920" height="911" alt="Dropdown tags overlap" src="https://github.com/user-attachments/assets/30462ca4-f231-4c62-adef-08ae2a7129cc" />

- [x] By default, **Hover Highlight** should be set to **true**.

- [x] **Single Selection Mode** is not working when the CRUD column is configured. This behaviour worked differently in previous release branches. Please cater for this scenario.  
[Test Form](https://linux-functional-adminportal-test.azurewebsites.net/dynamic/Boxfusion.SheshaFunctionalTests.Common/test-new-datatable)

- [x] Update the alert for **On Row Save** to include the text:  
_“This handler should return an object or a Promise<object>”_.  
Refer to older branches.

- [ ] Validation messages are cut off when performing inline editing.

<img width="1919" height="590" alt="Validation message cut off" src="https://github.com/user-attachments/assets/297c5bd2-50b3-49e6-9746-e4454117a8ac" />

- [x] **Backgrounds not working** – Only color works; other background properties do not work.  
**Not implemented – Awaiting @teboho**

- [x] **Name padding** should map to **Cell Padding**.

<img width="1918" height="832" alt="Name padding vs cell padding" src="https://github.com/user-attachments/assets/8d693f3e-f471-468f-891a-8c7eddd1ea30" />

- [x] **Sticky Header** works only in Preview. It does not work on Dynamic forms.  
Use this [form](https://linux-functional-adminportal-test.azurewebsites.net/dynamic/Boxfusion.SheshaFunctionalTests.Common/test-table-form) on Dynamic.

- [ ] It is unclear whether the **table body font** should apply to the CRUD and Action columns.

<img width="1503" height="752" alt="Table body font application" src="https://github.com/user-attachments/assets/ce2dbc41-f2a3-45ba-af16-5e2ea21b764b" />

- [ ] Padding and margin are still not applying correctly.

- [ ] **Row dimension and padding** under **Table Body Styles** are also applied to the header. These should apply only to the table body.

- [ ] **Custom Styles placement** – Custom styles should always be applied at the bottom.

- [ ] **Cell Text Color** duplicates the behaviour of **Table Body Font Color**, and **Cell Background Color** duplicates the behaviour of **Table Body Background Color**. Consider moving these JS settings to the Table Body and removing the duplicated properties.

- [ ] **On Row Double Click** fails to read `selectedRow.id` configured in the parameter when the configured action is either **Navigation** or **Show Dialog**.

- [ ] Form fields are cut off when **Form Column Type** is used for row edit and display.

<img width="1522" height="1008" alt="Image" src="https://github.com/user-attachments/assets/283f8b8e-4dc1-4854-8ae0-ffdf23329038" />


- [ ] When you have On Row Click Configured and you perform inline editing, when you click inside the input field it triggers the On Row Click Event.

**Comment by yuliaGradova** [comment]
Fix action and crud operation icon size: for some forms they're too small, for some forms they're huge
[Small icons](https://linux-functional-adminportal-test.azurewebsites.net/configuration-studio?docId=b64eb569-cf3d-4417-a2b9-02456e7d6540)
[Huge icons](https://linux-functional-adminportal-test.azurewebsites.net/dynamic/Boxfusion.SheshaFunctionalTests.ModuleA/MemberTable)

**Comment by James-Baloyi** [comment]
Questions for QA/Product:                                                                                                               
  - Current situation:                                                                                                                    
    - "Cell Text Color" duplicates "Table Body Font Color"                                                                                
    - "Cell Background Color" duplicates "Table Body Background Color"                                                                    
  - Proposed solution: Remove the duplicate Cell properties and use only Table Body properties                                            
  - Questions:                                                                                                                            
    - Should we consolidate these into single properties?                                                                                 
    - Which naming convention should we keep?                                                                                             
    - Are there any edge cases where separate properties are needed?                                                                      
    - Should this be a breaking change or should we migrate existing configurations?

**Comment by Tshepiso-R** [comment]
Hi @James-Baloyi, I agree with the proposed solution.

> **Should we consolidate these into single properties?**  

Yes, this should be a single property.

> **Which naming convention should we keep?**  

We should retain the font configuration under Table Body Styles.  
Also, please ensure that all properties under Table Body Styles follow the standard property order and that this order is consistent with the rest of the components.

> **Are there any edge cases where separate properties are needed?**  

I’m not aware of any. Currently, the behaviour is the same, so whatever one can do, the other should also be able to do.

> **Should this be a breaking change or should we migrate existing configurations?**  

To avoid form reconfiguration and breaking existing projects, migration should always be the first approach. A breaking change should only be considered if migration is not possible.

**Comment by Mluleki03** [comment]
- [x] The column name boundary lines do not align with table lines.
<img width="1601" height="330" alt="Image" src="https://github.com/user-attachments/assets/8494c2e3-b900-49d7-a42a-c2233b18ffcc" />

- [ ] The search bar on the properties panel, works for even the tab bar in an instance where navigating to the other tabs it is disabled.  Note it happens on designer.

- [ ] Export table data using Export Button is not working.

- [x] The **table body font**, only applies to default components.

- [x] Background properties are not working, only color works; other background properties do not persist. They briefly appear on render when refreshing the page. [Video](https://jam.dev/c/911fc3e7-25eb-43d2-a406-0d6853cf6512). The background setting for the table is obscured by the table rows, such you have to configure padding to see it.

- [x] Issue still persists:
> * [x]  **Row dimension and padding** under **Table Body Styles** are also applied to the header. These should apply only to the table body.

- [x] Issue still not resolved:
 > [ ] **On Row Double Click** fails to read `selectedRow.id` configured in the parameter when the configured action is either **Navigation** or **Show Dialog**.

- [x] Issue still occurring:
> [ ] When you have On Row Click Configured and you perform inline editing, when you click inside the input field it triggers the On Row Click Event.

[form](https://linux-functional-adminportal-test.azurewebsites.net/dynamic/Boxfusion.SheshaFunctionalTests.Web/DATATABLE)

**Comment by James-Baloyi** [comment]
@Mluleki03 as discussed
re:
"Background properties are not working, only color works; other background properties do not persist. They briefly appear on render when refreshing the page. [Video](https://jam.dev/c/911fc3e7-25eb-43d2-a406-0d6853cf6512). The background setting for the table is obscured by the table rows, such you have to configure padding to see it."

The background styles do apply but are hidden under the row background styles

**Comment by James-Baloyi** [comment]
@Mluleki03 
"Export table data using Export Button is not working."

The endpoint (/api/services/app/Entities/ExportToExcel) is failing to create a blob. There's not much we can do on the front-end

**Comment by Mluleki03** [comment]
- [x] On designer, scrolling past the default view on a table. Some shadow dividers appear, also the table colour changes after these.

<img width="896" height="619" alt="Image" src="https://github.com/user-attachments/assets/79530176-54d4-4628-8b5f-70508ad79caf" />

<img width="1102" height="461" alt="Image" src="https://github.com/user-attachments/assets/51607794-e513-45ee-a56c-1df7a56b4947" />

- [x] Column boundary lines appear cutoff

<img width="1102" height="461" alt="Image" src="https://github.com/user-attachments/assets/2fe87cf5-1e43-4a90-93ff-b9957c721fb7" />

- [ ] Still occurring

> * [x]  Issue still not resolved:
> 
> > [ ] **On Row Double Click** fails to read `selectedRow.id` configured in the parameter when the configured action is either **Navigation** or **Show Dialog**.

- [x] The background for the table seems to take 2 themes on designer, one being for the actual table and the other seen when  change row background

<img width="1181" height="396" alt="Image" src="https://github.com/user-attachments/assets/df35ae3f-4e07-40c3-8f95-41c8c6c78c31" />

- [ ] [FORM](https://linux-functional-adminportal-test.azurewebsites.net/dynamic/Boxfusion.SheshaFunctionalTests.Web/lateDataTable)

**Comment by James-Baloyi** [comment]
[https://linux-functional-adminportal-test.azurewebsites.net/configuration-studio?docId=b64eb569-cf3…](https://linux-functional-adminportal-test.azurewebsites.net/configuration-studio?docId=b64eb569-cf3d-4417-a2b9-02456e7d6540)



[https://linux-functional-adminportal-test.azurewebsites.net/dynamic/Boxfusion.SheshaFunctionalTests…](https://linux-functional-adminportal-test.azurewebsites.net/dynamic/Boxfusion.SheshaFunctionalTests.ModuleA/MemberTable)

Icon Sizing is addressed as well

**Comment by Mluleki03** [comment]
- [ ] Still occuring

> * On designer, scrolling past the default view saw on a table. Some shadow dividers appear, also the table colour changes after these

<img width="520" height="705" alt="Image" src="https://github.com/user-attachments/assets/a34ac072-8ca1-4caf-8584-790b7a762eef" />

- [ ] Column boundaries not showing
[Form](https://linux-functional-adminportal-test.azurewebsites.net/dynamic/Boxfusion.SheshaFunctionalTests.Web/newtable5)
<img width="1111" height="582" alt="Image" src="https://github.com/user-attachments/assets/a05a445f-9729-41e5-8667-dbd6d69b769f" />

- [x] On designer the entity reference becomes transparent with the header section 

<img width="904" height="537" alt="Image" src="https://github.com/user-attachments/assets/2db90a5c-d5f0-4a89-8852-1d90611be2c5" />

- [x] Stored File background, is not working 
[Form](https://linux-functional-adminportal-test.azurewebsites.net/dynamic/Boxfusion.SheshaFunctionalTests.Web/lateDataTable)
