### ISSUE TITLE
Property adjustment for 'Side Menu'

### ISSUE THREAD

**Issue by hlayisanimazuze** [shesha-io/shesha-framework#3127]
- In Settings >> Frontend Key >> Main Menu Settings >> Add a New Item, the layout of the configuration properties is distorted

![Image](https://github.com/user-attachments/assets/e266c14c-91e7-4580-a229-d99799eef07b)

**Comment by hlayisanimazuze** [comment]
Hi @teboho, please check this issue also while working on your settings-menu too

![Image](https://github.com/user-attachments/assets/66a2fabe-00b4-4840-8a08-0ca2e0f86989)

**Comment by hlayisanimazuze** [comment]
Hi @teboho, 

- When configuring a group or menu item, the changes are not reflected in the UI immediately, they only appear after the menu dialog is saved
Note: We had similar issue on Wizard and Tab before, it was fixed. Consult with @czwe-01 

![Image](https://github.com/user-attachments/assets/56e08b14-c603-4850-be51-23237eea91d2)

**Comment by hlayisanimazuze** [comment]
Hi @teboho, outside what Ian suggested about the button, I made a comment above with regards to:

- When configuring a group or menu item, the changes are not reflected in the UI immediately, they only appear after the menu dialog is saved. This is affecting both quick edit and the settings one. See: https://jam.dev/c/5f429a96-d2e3-490c-bb1a-70d05cb742d5
- Another thing we mentioned is that when users use the settings menu option instead of quick edit, clicking 'OK' should immediately reflect the newly saved menu item on the side menu, without requiring the main page to be saved
- With regards to the Configure Menu button, I asked @AlexanderSlavchovUX to check it and suggest ways to make it look nicer

**Comment by teboho** [comment]
> Hi @teboho, outside what Ian suggested about the button, I made a comment above with regards to:
> 
> - When configuring a group or menu item, the changes are not reflected in the UI immediately, they only appear after the menu dialog is saved. This is affecting both quick edit and the settings one. See: https://jam.dev/c/5f429a96-d2e3-490c-bb1a-70d05cb742d5

Latest related PR covers this one 


> - Another thing we mentioned is that when users use the settings menu option instead of quick edit, clicking 'OK' should immediately reflect the newly saved menu item on the side menu, without requiring the main page to be saved

This one has been covered in the previous related PR also


> - With regards to the Configure Menu button, I asked @AlexanderSlavchovUX to check it and suggest ways to make it look nicer

👍

**Comment by Tshepiso-R** [comment]
Hi @Teboho,

When configuring a menu item and setting the action configuration to Show Dialog with custom buttons, on initial Item Type defaults to "Item" instead of "Button." Even after changing it to "Button," the change doesn’t seem to reflect. Despite saving and refreshing, the custom buttons still do not appear, this might be related to the issue in the link below
https://jam.dev/c/6d8ce0a6-c5ea-47a9-a5b0-b67eefe34e45

**Comment by teboho** [comment]
> Hi [@teboho](https://github.com/teboho),
> 
> When configuring a menu item and setting the action configuration to Show Dialog with custom buttons, on initial Item Type defaults to "Item" instead of "Button." Even after changing it to "Button," the change doesn’t seem to reflect. Despite saving and refreshing, the custom buttons still do not appear, this might be related to the issue in the link below https://jam.dev/c/6d8ce0a6-c5ea-47a9-a5b0-b67eefe34e45

@Tshepiso-R this issue is not local to the menu, it is actually an action configuration issue and so should be moved to there

**Comment by Tshepiso-R** [comment]
> Hi [@teboho](https://github.com/teboho),
> 
> When configuring a menu item and setting the action configuration to Show Dialog with custom buttons, on initial Item Type defaults to "Item" instead of "Button." Even after changing it to "Button," the change doesn’t seem to reflect. Despite saving and refreshing, the custom buttons still do not appear, this might be related to the issue in the link below https://jam.dev/c/6d8ce0a6-c5ea-47a9-a5b0-b67eefe34e45
> 
> @Tshepiso-R this issue is not local to the menu, it is actually an action configuration issue and so should be moved to there 

Hi @teboho, this issue does not occure on the button. Please check this issue on main and investigate.

**Comment by teboho** [comment]
@Tshepiso-R currently in PR..
The real time (preview changes is a much more involved problem in that an attempt to fix it now affects other parts of the system: button group being one of them.. so it should be addressed on a separate issue card. For now a user will have to save by `Click Ok` on the modal to see their changes to the Side / Main menu

**Comment by yuliaGradova** [comment]
@teboho
please fix it for the current release since we don't have stable button group component yet. And we need this release as much stable as possible since after we release this branch the broken changes will be deployed into main
