### ISSUE TITLE
Data Table 'Customize Columns' JS Option Throws e.forEach is not a function Error

### ISSUE THREAD

**Issue by Tshepiso-R** [shesha-io/shesha-framework#3746]
## Describe the Bug
When using the **JS** option to configure **"Customize Columns"** on the data table, the following error is displayed:

## To Reproduce
1. Create a table view.
2. Click **Data Table**.
3. Click **JS** for **"Customize Column"**.
4. Console log the output.

## Expected Behavior
The component should not crash and should work as expected without throwing the `e.forEach` error.

## Screenshots
![Error Screenshot](https://github.com/user-attachments/assets/f6f6f7df-717c-4be4-ac37-953220845a87)

## Additional Notes:
This should be pushed to release 0.43 and the JS  button should be added to main(0.44)

**Comment by yuliaGradova** [comment]
Fixed and tested in 0.43. It has to be merged to 0.44 and main

**Comment by AlexStepantsov** [comment]
Fixeed with #3846

**Comment by yuliaGradova** [comment]
@AlexStepantsov we need to fix it on 0.44 also. It fixed on 0.43 and main

**Comment by AlexStepantsov** [comment]
@yuliaGradova fixed for 0.44

**Comment by miracleMa** [comment]
Hi @AlexStepantsov  
The issue is still reproducible on v44
https://jam.dev/c/2e70cad6-c02f-4e63-95e8-234463ccc2ed

**Comment by AlexStepantsov** [comment]
fixed for 0.44
