### ISSUE TITLE
Audit log  form is not logging the changes made on the form

### ISSUE THREAD

**Issue by miracleMa** [shesha-io/shesha-framework#3779]
**To Reproduce**
1. Go to 'https://linux-functional-adminportal-test.azurewebsites.net/dynamic/TestModule/views-table'
2. Drill down the details
3. edit  properties listed on the alert 
4. See error : the description  of the changed are not logged

**Expected behavior**

To log the following  properties : Date , action by , and description

**Comment by HackGenesis** [comment]
@miracleMa we cannot package shesha modules at the moment

**Comment by miracleMa** [comment]
HI @HackGenesis The issue is fixed, but we will close it once we are able to package Shesha forms.

**Comment by HackGenesis** [comment]
@miracleMa leave it on ready for testing

**Comment by miracleMa** [comment]
### 🐞 Audit Log Form Error – Suspected Endpoint Query Parameter Change

The **Audit Log** form is pulling data because of a failing endpoint.

#### 🔁 Steps to Reproduce

1. Open the link:
   [https://linux-functional-adminportal-test.azurewebsites.net/dynamic/Boxfusion.SheshaFunctionalTests.Common/views-details?id=2d5ff911-d548-432d-8084-08b3f91b45d7](https://linux-functional-adminportal-test.azurewebsites.net/dynamic/Boxfusion.SheshaFunctionalTests.Common/views-details?id=2d5ff911-d548-432d-8084-08b3f91b45d7)

2. Ensure you are in **Edit** mode.

3. Open **Developer Tools → Network**.

4. Click the **Audit Log** button.

5. Open the **Edit Entity Audit Log** form.

#### ❌ Actual Result

An error occurs and the request to the **GetAuditTrail** endpoint fails (see attached screenshot).

<img width="1896" height="962" alt="Image" src="https://github.com/user-attachments/assets/a5b62fb2-bb93-4b93-ad15-de93c0512c54" />

<img width="1896" height="962" alt="Image" src="https://github.com/user-attachments/assets/7832008c-9f93-4aa4-9e67-88710f4fd415" />

#### ✅ Expected Result

The Audit Log form should load and display the entity’s audit trail without errors.

#### 🔍 Additional Notes

It is assumed that the issue is caused by a **change in the endpoint’s query parameters**, which the frontend is no longer matching correctly.

<img width="2412" height="1245" alt="Image" src="https://github.com/user-attachments/assets/6e49f720-b340-427f-bd86-2d74ad86c354" />

---
.

**Comment by HackGenesis** [comment]
@yuliaGradova i am not getting the same error on the screenshot, I cannot replicate, also can you please check if Shesha.Domain.ShaRoleAppointedPerson still exist on 46

<img width="1470" height="471" alt="Image" src="https://github.com/user-attachments/assets/6af92279-cf51-4d72-be35-1083f5283e47" />

**Comment by zukidlomo** [comment]
The initial issue (https://github.com/shesha-io/shesha-framework/issues/3779#issue-3375548810) is back.

Form: https://[linux-functional-adminportal-test.azurewebsites.net/dynamic/Boxfusion.SheshaFunctionalTests.Web/DetailsRework?id=9d84d079-cd07-4925-8468-077b0f6cec07](https://linux-functional-adminportal-test.azurewebsites.net/dynamic/Boxfusion.SheshaFunctionalTests.Web/DetailsRework?id=9d84d079-cd07-4925-8468-077b0f6cec07)

The "TextFieldString" is marked as Audited on [Entity Settings](https://linux-functional-adminportal-test.azurewebsites.net/configuration-studio?docId=685399bb-6532-413e-a0f5-ea82dab2ca02). However, when I edit it, the audit log form does not display changes made.

** @HackGenesis  Browser issue, changes do not display when made in Edge browser

**Comment by yuliaGradova** [comment]
@HackGenesis fix description field. [Form link](https://linux-functional-adminportal-test.azurewebsites.net/dynamic/Boxfusion.SheshaFunctionalTests.Web/DetailsRework?id=9d84d079-cd07-4925-8468-077b0f6cec07)

<img width="2060" height="434" alt="Image" src="https://github.com/user-attachments/assets/8db76e4c-2619-4875-8b23-2af8c51f55ea" />

**Comment by zukidlomo** [comment]
The data for Actioned By, Change Type and Description are not showing. Only the date shows.

Form: https://linux-functional-adminportal-test.azurewebsites.net/dynamic/Boxfusion.SheshaFunctionalTests.Web/DetailsRework?id=9d84d079-cd07-4925-8468-077b0f6cec07

<img width="1912" height="952" alt="Image" src="https://github.com/user-attachments/assets/a00d0628-9948-4184-b9cc-3a3dedabc846" />

**Comment by AlexStepantsov** [comment]
Fixed 

shesha-reactjs/src/providers/form/utils.ts

https://github.com/shesha-io/shesha-framework/pull/5423/changes/b4b3c8d536617abffc7e95c23ebada5f7611d678#diff-24f7795289c98ae783ed0f39b064c6e2524b5df4521d0edbd2781fc87355dcc9

**Comment by yuliaGradova** [comment]
Audit record created but description is shown as }
[Form link ](https://linux-functional-v0-46-adminportal-test.azurewebsites.net/dynamic/Boxfusion.SheshaFunctionalTests.ModuleA/MemberDetails46?id=4d0e6e68-5724-499e-a145-01cb11bf9cfe)

<img width="1534" height="377" alt="Image" src="https://github.com/user-attachments/assets/e06da3d6-3049-4530-a2b0-54803cc36de5" />
